version: "3"

services:
    antora-build:
        build: .
        volumes:
            - ../../:/workdir
        ports:
            - 3000:3000
            - 3001:3001
        command: /bin/sh -c "watch antora --to-dir /public/ antora-playbook-author-mode.yml & browser-sync start --server '/public' --watch --no-open false"
